version: '3'
services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongo-db:/data/db
    
  contact-manager:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    networks:
      - mynetwork
  
volumes:
  mongo-db:

networks:
  mynetwork:
    driver: bridge


